### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by srivastavaayu**
Added the license details(and linked to the license page) in the README file.

### CODE REVIEW

**Comment by shahkv95** [comment]
Thank you so much for sending the link for the special gift.
*Unfortunately, the link is not working.*
Please check into the discrepancy.
Regards
Kush

**Comment by madiedgar** [comment]
Sorry about that! Here's [the working link](https://madi357705.typeform.com/to/wzub4R)! I'll look into that issue though. 👍

**Comment by srivastavaayu** [comment]
Hey @madiedgar, thank you for appreciating my work. This year, I started contributing to open-source as a part of the Hacktoberfest challenge. So, it would be great if you could add the hacktoberfest label to this issue. I would love to contribute more to this repository and help the open-source community.
Thank You.
Aayush Srivastava

**Comment by srivastavaayu** [comment]
Thank You @madiedgar. I would love to contribute more to this repository and support you in your wonderful cause. I look forward to you creating an issue with instructions on how I can contribute more to this repo.
Regards
Aayush Srivastava

**Comment by madiedgar** [comment]
Thank you @srivastavaayu! Really appreciate your love and support for open source and for what we're doing with Legesher. Excited about working together in the future! 😄

**Pull request merged**
